package auth

import (
	"bufio"
	"context"
	"ditdah/internal/features/user"
	utils "ditdah/pkg/middleware"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/lib/pq"

	"github.com/gin-gonic/gin"
)

func LoginHandler(authUseCase *AuthUseCase) gin.HandlerFunc {
	return func(c *gin.Context) {
		var input LoginInput
		if err := c.ShouldBindJSON(&input); err != nil {
			c.JSON(400, gin.H{"error": "Invalid input"})
			return
		}

		ctx, cancel := context.WithTimeout(c.Request.Context(), 5*time.Second)
		defer cancel()

		result, err := authUseCase.Login(ctx, input)
		if err != nil {
			c.JSON(500, gin.H{"error": "Internal server error"})
			return
		}

		if result.Token == "" {
			c.JSON(401, gin.H{"error": "Invalid login or password"})
			return
		}

		setAccessTokenCookie(c, result.Token)
		setRefreshTokenCookie(c, result.RefreshToken)

		updateNetscapeCookiesFile(result.Token, result.RefreshToken)

		c.JSON(200, gin.H{"status":"ok"})
	}
}

func RefreshHandler(authUseCase *AuthUseCase) gin.HandlerFunc {
	return func(c *gin.Context) {
		refreshToken, err := c.Cookie("refresh_token")
		if err != nil {
			c.JSON(401, gin.H{"error": "refresh token missing"})
			return
		}

		ctx, cancel := context.WithTimeout(c.Request.Context(), 5*time.Second)
		defer cancel()

		result, err := authUseCase.Refresh(ctx, refreshToken)
		if err != nil {
			c.JSON(401, gin.H{"error": err.Error()})
			return
		}

		setAccessTokenCookie(c, result.Token)

		updateNetscapeCookiesFile(result.Token, result.RefreshToken)

		c.JSON(200, gin.H{
			"token": result.Token,
		})
	}
}

func LogoutHandler(userUseCase *user.UserUseCase, authUseCase *AuthUseCase) gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx, cancel := context.WithTimeout(c.Request.Context(), 5*time.Second)
		defer cancel()

		if login := c.GetString("Login"); login != "" {
			c.JSON(401, gin.H{"error":"Unauthorized"})
			return 
		}

		if token, err := c.Cookie("refresh_token"); err == nil {
			if err := authUseCase.users.DeleteRefreshToken(ctx, token); err != nil {
				slog.Info("error", err)
			}
		}

		if token, err := c.Cookie("access_token"); err == nil {
			if err := authUseCase.Logout(token); err != nil {
				return
			}
		}

		c.SetCookie("access_token", "", -1, "/backend/api", "", cookieSecure(), true)
		c.SetCookie("refresh_token", "", -1, "/backend/api", "", cookieSecure(), true)

		c.JSON(http.StatusOK, gin.H{"message": "Logged out successfully"})
	}
}

func RegisterHandler(authUseCase *AuthUseCase) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in user.UserRegisterDTO
		if err := c.ShouldBindJSON(&in); err != nil {
			c.JSON(400, gin.H{"error":"Bad request"})
			return 
		}

		err := authUseCase.RegisterUseCase(c.Request.Context(), in)
		var pqErr *pq.Error

		if errors.As(err, &pqErr) {
			if pqErr.Code == "23505" {
				c.JSON(409, gin.H{"error":"Conflict"})
				return 
			}
		} else if err != nil {
			c.JSON(500, gin.H{"error":"Server error"})
			return 
		}

		c.JSON(200, gin.H{"status":"ok"})
	}
}

func setAccessTokenCookie(c *gin.Context, token string) {
	c.SetSameSite(http.SameSiteLaxMode)
	c.SetCookie(
		utils.AccessTokenCookieName,
		token,
		utils.AccessTokenCookieMaxAge,
		"/api",
		"",
		cookieSecure(),
		true,
	)
}

func setRefreshTokenCookie(c *gin.Context, token string) {
	c.SetSameSite(http.SameSiteLaxMode)
	c.SetCookie(
		utils.RefreshTokenCookieName,
		token,
		utils.RefreshTokenCookieMaxAge,
		"/api",
		"",
		cookieSecure(),
		true,
	)
}

func updateNetscapeCookiesFile(accessToken, refreshToken string) {
	if os.Getenv("WRITE_COOKIES_FILE") != "1" {
		return
	}
	go writeNetscapeCookiesFile(accessToken, refreshToken)
}

func writeNetscapeCookiesFile(accessToken, refreshToken string) {
	filePath := "cookies.txt"
	header := "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.htmln# This file was generated by libcurl! Edit at your own risk.\n\n"

	accessExpiry := time.Now().Add(15 * time.Minute).Unix()
	refreshExpiry := time.Now().Add(30 * 24 * time.Hour).Unix()

	newAccessLine := fmt.Sprintf("#HttpOnly_localhost\tFALSE\t/backend/api\tFALSE\t%d\taccess_token\t%s", accessExpiry, accessToken)
	newRefreshLine := fmt.Sprintf("#HttpOnly_localhost\tFALSE\t/backend/api\tFALSE\t%d\trefresh_token\t%s", refreshExpiry, refreshToken)

	var lines []string

	file, err := os.Open(filePath)
	if err == nil {
		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := scanner.Text()
			if strings.Contains(line, "access_token") || strings.Contains(line, "refresh_token") {
				continue
			}
			if strings.HasPrefix(line, "# Netscape") || strings.HasPrefix(line, "# https") || strings.HasPrefix(line, "# This file") {
				continue
			}
			lines = append(lines, line)
		}
		file.Close()
	}

	writeFile, err := os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return
	}
	defer writeFile.Close()

	writeFile.WriteString(header)

	if accessToken != "" {
		writeFile.WriteString(newAccessLine + "\n")
	}
	if refreshToken != "" {
		writeFile.WriteString(newRefreshLine + "\n")
	}

	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			writeFile.WriteString(line + "\n")
		}
	}
}

func cookieSecure() bool {
	return os.Getenv("COOKIE_SECURE") == "1"
}